2020-01-09 13:36:08,673  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 13:36:08,685  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7f81f5075780>  
2020-01-09 13:39:04,197  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_82c006ba-0c0b-40d7-ad84-096a12ac3349_1039  
2020-01-09 13:39:04,758  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 13:39:04,979  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_705ebcde-5a78-4826-980f-8d077d040a45_1114  
2020-01-09 13:39:05,245  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:05,246  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:06,453  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 13:39:07,244  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:07,245  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:08,199  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:08,200  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:08,651  ERROR  25  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [OrderedDict([('id', 1), ('name', '3C Appliances'), ('avatar', '/media/products/377c212f2cad404992681f321a9eb78b.jpeg'), ('slug', '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959'), ('subcatalogues', [OrderedDict([('id', 1), ('name', 'HP PC'), ('avatar', '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg'), ('slug', 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('url', 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('product_num', 3)])])])]}  
2020-01-09 13:39:08,896  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:08,898  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:09,466  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:09,466  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:09,780  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:09,781  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:10,096  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 13:39:10,284  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:10,285  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:10,526  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:10,537  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:10,943  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:10,944  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:11,143  ERROR  28  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 13:39:11,391  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 13:39:11,392  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0ba0a20>  
2020-01-09 13:39:11,474  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:11,475  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:15,261  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:15,262  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:15,358  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:15,358  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:15,462  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:15,463  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:16,188  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:39:16,189  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:39:16,340  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 13:47:32,477  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:47:32,517  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:47:32,587  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 13:47:33,553  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 13:47:33,656  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:47:33,658  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:47:34,481  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 13:47:34,483  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0bbe0f0>  
2020-01-09 13:48:34,547  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:48:34,550  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:48:34,773  ERROR  25  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 13:48:35,324  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 13:48:35,476  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:48:35,481  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:48:36,609  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 13:48:36,609  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b092aba8>  
2020-01-09 13:50:37,705  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:37,706  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:50:37,839  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:37,841  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:50:38,380  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:38,381  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:50:38,459  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 13:50:38,533  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:38,534  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:50:38,616  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:38,616  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 13:50:38,696  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 13:50:38,696  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:40:19,810  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:40:19,811  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:40:19,932  ERROR  25  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:40:19,941  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [OrderedDict([('id', 1), ('name', '3C Appliances'), ('avatar', '/media/products/377c212f2cad404992681f321a9eb78b.jpeg'), ('slug', '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959'), ('subcatalogues', [OrderedDict([('id', 1), ('name', 'HP PC'), ('avatar', '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg'), ('slug', 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('url', 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('product_num', 3)])])])]}  
2020-01-09 14:40:20,168  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:40:20,170  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:40:20,966  ERROR  26  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:40:20,969  ERROR  26  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0a8ca20>  
2020-01-09 14:44:16,209  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:44:16,216  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:44:16,278  ERROR  26  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:44:16,444  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:44:16,999  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:44:17,045  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:44:17,834  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:44:17,835  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0587860>  
2020-01-09 14:45:48,992  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:45:48,995  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:45:49,396  ERROR  31  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:45:49,653  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:45:49,654  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:45:49,789  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:45:50,911  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:45:50,944  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b03ba278>  
2020-01-09 14:48:56,171  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:48:56,173  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:48:56,193  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:48:56,785  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:48:56,800  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:48:56,804  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:48:57,966  ERROR  26  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:48:57,969  ERROR  26  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b09c49e8>  
2020-01-09 14:51:22,042  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:51:22,045  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:51:22,470  ERROR  25  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:51:22,582  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [OrderedDict([('id', 1), ('name', '3C Appliances'), ('avatar', '/media/products/377c212f2cad404992681f321a9eb78b.jpeg'), ('slug', '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959'), ('subcatalogues', [OrderedDict([('id', 1), ('name', 'HP PC'), ('avatar', '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg'), ('slug', 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('url', 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('product_num', 3)])])])]}  
2020-01-09 14:51:22,618  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:51:22,675  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:51:24,404  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:51:24,405  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b07a6fd0>  
2020-01-09 14:52:57,302  ERROR  26  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:52:57,303  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:52:57,358  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:52:57,772  ERROR  26  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:52:57,879  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:52:57,937  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:52:58,511  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:52:58,511  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0770828>  
2020-01-09 14:56:37,489  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:56:37,491  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:56:37,915  ERROR  26  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:56:38,065  ERROR  28  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:56:38,217  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:56:38,218  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:56:39,817  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:56:39,818  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b068d780>  
2020-01-09 14:57:29,952  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:57:30,059  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:57:30,143  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:57:30,404  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:57:30,509  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:57:30,511  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:57:32,487  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:57:32,488  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b066f6a0>  
2020-01-09 14:58:16,471  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:58:16,485  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:58:16,604  ERROR  25  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 14:58:16,778  ERROR  25  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 14:58:16,861  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 14:58:16,863  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 14:58:18,633  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 14:58:18,636  ERROR  25  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b04e4dd8>  
2020-01-09 15:20:15,692  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:15,694  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:15,798  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:15,801  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:15,899  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:15,899  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:16,021  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:16,021  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:16,139  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:16,140  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:16,233  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 15:20:16,234  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 15:20:16,319  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 17:10:03,239  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:10:03,240  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:10:03,622  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 17:10:03,630  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:10:03,645  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:10:03,878  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [OrderedDict([('id', 1), ('name', '3C Appliances'), ('avatar', '/media/products/377c212f2cad404992681f321a9eb78b.jpeg'), ('slug', '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959'), ('subcatalogues', [OrderedDict([('id', 1), ('name', 'HP PC'), ('avatar', '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg'), ('slug', 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('url', 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918'), ('product_num', 3)])])])]}  
2020-01-09 17:10:05,524  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 17:10:05,525  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b09693c8>  
2020-01-09 17:11:40,470  ERROR  25  /django_project/shoppingcart/viewsets.py  bySlug  524  fbfb3a68-e067-4d92-9475-68058109988e0200  
2020-01-09 17:11:43,920  ERROR  25  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 17:11:44,020  ERROR  31  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 17:11:44,614  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:11:44,616  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:11:44,930  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:11:44,938  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:11:57,337  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 17:11:57,338  ERROR  31  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b07c9f98>  
2020-01-09 17:12:00,326  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:12:00,327  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:12:00,786  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:12:00,951  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:12:00,972  ERROR  28  /django_project/lottery_shop/viewsets.py  list  65  {'type': 'list', 'catalogues': [{'id': 1, 'name': '3C Appliances', 'avatar': '/media/products/377c212f2cad404992681f321a9eb78b.jpeg', 'slug': '30e8c3eb-6c23-4cb9-b983-3a4b5eed796e_0959', 'subcatalogues': [{'id': 1, 'name': 'HP PC', 'avatar': '/media/products/1d88c45455f0429a94f18bb1f3b919ad.jpg', 'slug': 'c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'url': 'subcatalogue/c8d3a0fa-fabf-48b8-838c-e192b4607264_0918', 'product_num': 3}]}]}  
2020-01-09 17:12:01,550  ERROR  26  /django_project/useraccount/viewsets.py  AlsoLoginMeSync  174  AlsoLoginMeSync Good  
2020-01-09 17:12:59,908  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  541  testorders  
2020-01-09 17:12:59,909  ERROR  28  /django_project/shoppingcart/viewsets.py  UserOrderList  542  <shoppingcart.viewsets.UserOrderFilter object at 0x7fb8b0618d30>  
2020-01-09 17:13:01,936  ERROR  31  /django_project/shoppingcart/viewsets.py  bySlug  524  fbfb3a68-e067-4d92-9475-68058109988e0200  
2020-01-09 17:57:57,551  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:57,552  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:57:57,620  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:57,621  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:57:57,691  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 17:57:57,754  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:57,754  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:57:57,846  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:57,847  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:57:57,926  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:57,927  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 17:57:58,002  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 17:57:58,002  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:50,687  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:50,688  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:50,758  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:50,760  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:50,831  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:50,832  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:50,906  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:50,910  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:50,990  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:50,991  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
2020-01-09 18:08:51,062  ERROR  8  /django_project/rentalhouse/consumers.py  connect  24  rentalhouse_112c41af-8d5f-4f25-890d-2a81691a8327_0928  
2020-01-09 18:08:51,122  ERROR  8  /django_project/chat/consumers.py  connect  259  root connected to server  
2020-01-09 18:08:51,123  ERROR  8  /django_project/chat/consumers.py  connect  260  1  
